services:
  db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data
    restart: always
    env_file:
      - .env
  web:
    image: web
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    expose:
      - 3000
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    depends_on:
      - db
    env_file:
      - .env


